[package]
name = "WinBooster"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
glob = "0.3.1"
whoami = "1.5.2"
inquire = "0.7.5"
tabled = "0.17.0"
crossterm = "0.27.0"
tokio = { version = "1", features = ["full"] }
winreg = "0.52.0"
indicatif = "0.17.7"

[build-dependencies]
winres = "0.1"