[package]
name = "gui"
version = "0.1.0"
edition = "2024"

[dependencies]
glob = "0.3.1"
inquire = "0.7.5"
crossterm = "0.27.0"
tokio = { version = "1", features = ["full"] }
indicatif = "0.17.7"
notify-rust = "4"
tabled = "0.17.0"
database = { path = "../database" }
cleaner = { path = "../cleaner" }

[build-dependencies]
winres = "0.1"