[package]
name = "WinBooster_CLI"
version = "1.9.1"
edition = "2021"
build = "build.rs"

[dependencies]
glob = "0.3.1"
inquire = "0.7.5"
crossterm = "0.27.0"
tokio = { version = "1", features = ["full"] }
indicatif = "0.17.7"
notify-rust = "4"
tabled = "0.17.0"
database = { path = "../database" }
cleaner = { path = "../cleaner" }

[build-dependencies]
winres = "0.1"

[package.metadata.winres]
FileDescription = "Garbage remover"
OriginalFilename = "WinBooster.exe"
LegalCopyright = "Copyright Monolith Development © 2025"
ProductName = "WinBooster"
ProductVersion = "1.8.9"

[profile.release] # optimize file size
lto = true
codegen-units = 1
opt-level = "z"
strip = true
panic = "abort"
debug  = false