[package]
name = "database"
version = "0.1.0"
edition = "2024"

[dependencies]
tabled = "0.17.0"
whoami = "1.5.2"
lazy_static = "1.4"

[target.'cfg(windows)'.dependencies]
disk-name = "1.0.0"
winreg = "0.55.0"