name: Rust compile and release

on:
  push:
    branches: [ "main", "test" ]
  pull_request:
    branches: [ "main", "test" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux:

    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v4
    - name: Build linux
      run: cargo build --release
    - name: Move binary
      run: |
        mv target/release/Cross_Cleaner_CLI Cross_Cleaner_CLI
        mv target/release/Cross_Cleaner_GUI Cross_Cleaner_GUI
    - name: Archive Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Artifacts
        path: |
          Cross_Cleaner_CLI
          Cross_Cleaner_GUI
          ./database/linux_database.json
          ./database/windows_database.json

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: '${{ secrets.GITHUB_TOKEN }}'
        automatic_release_tag: "1.9.6"
        prerelease: true
        title: "1.9.6"
        files: |
            Cross_Cleaner_CLI
            Cross_Cleaner_GUI
            ./database/linux_database.json
            ./database/windows_database.json
  build_windows:

    runs-on: windows-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v4
    - name: Build windows
      run: cargo build --release
    - name: Move binary
      run: |
        mv target/release/Cross_Cleaner_CLI.exe Cross_Cleaner_CLI.exe
        mv target/release/Cross_Cleaner_GUI.exe Cross_Cleaner_GUI.exe
    - name: Archive Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Artifacts
        path: |
          Cross_Cleaner_CLI.exe
          Cross_Cleaner_GUI.exe
          ./database/linux_database.json
          ./database/windows_database.json

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: '${{ secrets.GITHUB_TOKEN }}'
        automatic_release_tag: "1.9.6"
        prerelease: true
        title: "1.9.6"
        files: |
            Cross_Cleaner_CLI.exe
            Cross_Cleaner_GUI.exe
            ./database/linux_database.json
            ./database/windows_database.json
