name: Rust compile and release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v4
    - name: Build linux
      run: cargo build --release
    - name: Setup windows target
      run: |
        sudo apt install build-essential
        sudo apt install gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64
        rustup target add x86_64-pc-windows-gnu
    - name: Build windows
      run: |
        cargo build --release --target=x86_64-pc-windows-gnu
    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: '${{ secrets.GITHUB_TOKEN }}'
        automatic_release_tag: "1.9.3"
        prerelease: true
        title: "1.9.3"
        files: |
            ./target/release/Cross_Cleaner_CLI
            ./target/release/Cross_Cleaner_GUI
            ./target/release/x86_64-pc-windows-gnu/*.exe
