name: Rust compile and release

on:
  push:
    branches: [ "main", "test" ]
  pull_request:
    branches: [ "main", "test" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v4
    - name: Build linux
      run: cargo build --release
    - name: Setup windows target
      run: |
        sudo apt install build-essential
        sudo apt install gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64
        rustup target add x86_64-pc-windows-gnu
    - name: Build windows
      run: |
        cargo build --release --target=x86_64-pc-windows-gnu
    - name: Archive Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Artifacts
        path: |
          ./target/release/Cross_Cleaner_CLI
          ./target/release/Cross_Cleaner_GUI
          ./target/x86_64-pc-windows-gnu/release/Cross_Cleaner_CLI.exe
          ./target/x86_64-pc-windows-gnu/release/Cross_Cleaner_GUI.exe

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: '${{ secrets.GITHUB_TOKEN }}'
        automatic_release_tag: "1.9.3b2"
        prerelease: true
        title: "1.9.3 Beta №2"
        files: |
            ./target/release/Cross_Cleaner_CLI
            ./target/release/Cross_Cleaner_GUI
            ./target/x86_64-pc-windows-gnu/release/Cross_Cleaner_CLI.exe
            ./target/x86_64-pc-windows-gnu/release/Cross_Cleaner_GUI.exe
