name: Rust compile and release

on:
  push:
    branches: [ "main", "test" ]
  pull_request:
    branches: [ "main", "test" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v4
    - name: Get version
      id: version
      run: echo "version=$(cargo pkgid | cut -d'#' -f2)" >> $GITHUB_OUTPUT
    - name: Build linux
      run: cargo build --release
    - name: Move binary
      run: |
        mv target/release/Cross_Cleaner_CLI Cross_Cleaner_CLI
        mv target/release/Cross_Cleaner_GUI Cross_Cleaner_GUI
    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-binaries
        path: |
          Cross_Cleaner_CLI
          Cross_Cleaner_GUI

  build_windows:
    runs-on: windows-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v4
    - name: Build windows
      run: cargo build --release
    - name: Move binary
      run: |
        move target\release\Cross_Cleaner_CLI.exe Cross_Cleaner_CLI.exe
        move target\release\Cross_Cleaner_GUI.exe Cross_Cleaner_GUI.exe
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-binaries
        path: |
          Cross_Cleaner_CLI.exe
          Cross_Cleaner_GUI.exe

  create_release:
    needs: [build_linux, build_windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Get version
      id: version
      run: echo "version=$(cargo pkgid | cut -d'#' -f2)" >> $GITHUB_OUTPUT
    - name: Download Linux artifacts
      uses: actions/download-artifact@v4
      with:
        name: linux-binaries
        path: linux-binaries
    - name: Download Windows artifacts
      uses: actions/download-artifact@v4
      with:
        name: windows-binaries
        path: windows-binaries
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.version.outputs.version }}
        name: Cross Cleaner ${{ steps.version.outputs.version }}
        files: |
          linux-binaries/Cross_Cleaner_CLI
          linux-binaries/Cross_Cleaner_GUI
          windows-binaries/Cross_Cleaner_CLI.exe
          windows-binaries/Cross_Cleaner_GUI.exe
